openapi: 3.0.0
info:
  title: hello-service
  version: 1.0.0
servers:
  - url: http://localhost:8080
paths:
  /hello:
    post:
      tags:
        - default
      summary: create
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                n: 1
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
